-- 建表脚本（已修正语法）
CREATE TABLE `user` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `email` VARCHAR(255),
  `department` VARCHAR(15),
  `role` ENUM('ADMIN','USER','DOCTER'),
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `child` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `parent_id` BIGINT,
  `name` VARCHAR(255) NOT NULL,
  `gender` ENUM('男','女') NOT NULL,
  `birthdate` DATE NOT NULL,
  `height` DECIMAL(5,2),
  `weight` DECIMAL(5,2),
  `bmi` DECIMAL(5,2),
  `bone_age` DECIMAL(5,2),
  `test_date` DATE,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `prediction_result` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `child_id` BIGINT,
  `risk_level` ENUM('LOW','MID','HIGH') NOT NULL,
  `prediction_date` DATE NOT NULL,
  `model_version` VARCHAR(50) NOT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (`child_id`) REFERENCES `child`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `appointment` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `parent_id` BIGINT,
  `doctor_id` BIGINT,
  `appointment_time` DATETIME NOT NULL,
  `status` ENUM('UN_CONFIRM','CONFIRMED','CONCELED') NOT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `health_article` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `title` VARCHAR(255) NOT NULL,
  `content` TEXT NOT NULL,
  `author` VARCHAR(255) NOT NULL,
  `publish_date` DATE NOT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `feedback` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `parent_id` BIGINT,
  `content` TEXT NOT NULL,
  `reply` TEXT,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `log` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `action` VARCHAR(255) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `action_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `details` TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `message` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `receiver_id` BIGINT NOT NULL,
  `receiver_role` ENUM('USER','DOCTER','ADMIN') NOT NULL,
  `message` TEXT NOT NULL,
  `status` ENUM('UNREAD','READED') DEFAULT 'UNREAD',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `notification` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `receiver_id` BIGINT NOT NULL,
  `receiver_role` ENUM('USER','DOCTER','ADMIN') NOT NULL,
  `message` TEXT NOT NULL,
  `status` ENUM('UNREAD','READED') DEFAULT 'UNREAD',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
